//! Idempotent Flatpak overrides for Steam, Lutris, and Heroic.

use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

use metis_config::{
    GamingFlatpakState, detect_hybrid_gpu, display_gpu_pci, flatpak_env_arg, load_gaming_config,
    load_gaming_flatpak_state, offload_env_vars, sanitize_offload_env, save_gaming_flatpak_state,
    shell_export_line, validate_steam_library_path,
};

const GAMING_APPS: &[(&str, &[&str])] = &[
    (
        "com.valvesoftware.Steam",
        &[
            "--device=all",
            "--socket=wayland",
            "--socket=pulseaudio",
            "--share=network",
        ],
    ),
    ("net.lutris.Lutris", &["--device=all", "--share=network"]),
    (
        "com.heroicgameslauncher.hgl",
        &["--device=all", "--share=network"],
    ),
];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FlatpakOptimizeResult {
    pub app_id: String,
    pub applied: bool,
    pub message: String,
}

/// Apply gaming Flatpak overrides using sanitized `gaming.json` `extra_steam_paths`
/// and allowlisted GPU offload `--env` values.
pub fn optimize_flatpak_gaming() -> Result<Vec<FlatpakOptimizeResult>, String> {
    if !crate::detect::binary_in_path("flatpak") {
        return Err("flatpak not installed".into());
    }

    let cfg = load_gaming_config();
    let gpu_env = if cfg.flatpak_gpu_env {
        detect_hybrid_gpu(display_gpu_pci().as_deref())
            .map(|info| sanitize_offload_env(&offload_env_vars(&info)))
    } else {
        None
    };

    let mut steam_paths = Vec::new();
    for raw in &cfg.extra_steam_paths {
        match validate_steam_library_path(raw) {
            Some(canon) => steam_paths.push(canon.to_string_lossy().into_owned()),
            None => {
                tracing::warn!(
                    path = %raw,
                    "skipping invalid extra_steam_paths entry for Flatpak Steam"
                );
            }
        }
    }

    let mut results = Vec::new();
    let mut optimized = Vec::new();

    for (app_id, flags) in GAMING_APPS {
        if !crate::detect::flatpak_has_app(app_id) {
            continue;
        }
        let mut args: Vec<String> = vec!["override".into(), "--user".into()];
        for flag in *flags {
            args.push((*flag).into());
        }
        if let Some(env) = &gpu_env {
            for (key, val) in env {
                if let Some(kv) = flatpak_env_arg(key, val) {
                    args.push("--env".into());
                    args.push(kv);
                } else {
                    tracing::warn!(%key, "skipped unsafe Flatpak --env pair");
                }
            }
        }
        if *app_id == "com.valvesoftware.Steam" {
            for path in &steam_paths {
                args.push("--filesystem".into());
                args.push(path.clone());
            }
        }
        args.push((*app_id).into());

        let ok = Command::new("flatpak")
            .args(&args)
            .status()
            .map(|s| s.success())
            .unwrap_or(false);
        results.push(FlatpakOptimizeResult {
            app_id: (*app_id).to_string(),
            applied: ok,
            message: if ok {
                "overrides applied".into()
            } else {
                format!("flatpak override failed for {app_id}")
            },
        });
        if ok {
            optimized.push((*app_id).to_string());
        }
    }

    let state = GamingFlatpakState {
        optimized_apps: optimized,
        last_run_unix: SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .ok()
            .map(|d| d.as_secs()),
    };
    let _ = save_gaming_flatpak_state(&state);

    Ok(results)
}

/// Write `~/.local/share/metis/bin/launch-steam` with GPU env for Flatpak Steam.
pub fn ensure_steam_launcher() -> std::io::Result<std::path::PathBuf> {
    let home = std::env::var("HOME").map_err(std::io::Error::other)?;
    let bin_dir = std::path::Path::new(&home).join(".local/share/metis/bin");
    std::fs::create_dir_all(&bin_dir)?;
    let script_path = bin_dir.join("launch-steam");
    let mut script = String::from("#!/bin/sh\n# Generated by Metis gaming platform\n");
    let cfg = load_gaming_config();
    if cfg.flatpak_gpu_env
        && let Some(info) = detect_hybrid_gpu(display_gpu_pci().as_deref())
    {
        for (key, val) in sanitize_offload_env(&offload_env_vars(&info)) {
            if let Some(line) = shell_export_line(&key, &val) {
                script.push_str(&line);
            } else {
                tracing::warn!(%key, "skipped unsafe launch-steam export");
            }
        }
    }
    script.push_str("exec flatpak run com.valvesoftware.Steam \"$@\"\n");
    std::fs::write(&script_path, &script)?;
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(&script_path, std::fs::Permissions::from_mode(0o755))?;
    Ok(script_path)
}

pub fn flatpak_steam_launch_command(extra_args: &str) -> Option<String> {
    if !crate::detect::flatpak_has_app("com.valvesoftware.Steam") {
        return None;
    }
    if let Ok(path) = ensure_steam_launcher() {
        let base = path.to_string_lossy();
        if extra_args.trim().is_empty() {
            return Some(base.into_owned());
        }
        return Some(format!("{base} {extra_args}"));
    }
    if extra_args.trim().is_empty() {
        Some("flatpak run com.valvesoftware.Steam".into())
    } else {
        Some(format!("flatpak run com.valvesoftware.Steam {extra_args}"))
    }
}

pub fn flatpak_steam_needs_optimize() -> bool {
    let state = load_gaming_flatpak_state();
    crate::detect::flatpak_has_app("com.valvesoftware.Steam")
        && !state
            .optimized_apps
            .iter()
            .any(|a| a == "com.valvesoftware.Steam")
}
